export enum Operators {
    And = 0,
    Or = 1,
    Not = 2,
    Xor = 3,
    Equal = 4,
    NotEqual = 5,
    LessThan = 6,
    GreaterThan = 7,
    LessThanOrEqual = 8,
    GreaterThanOrEqual = 9,
    Contains = 10,
    StartGrouping = 11,
    EndGrouping = 12,
}